spring.application.name=ServerMonitor

#---App's features configuration

#JWT expiration time interval------
#----3600000 (1 hour for normal use)
#----60000 (1 minute for testing)
app.expirationTime = 60000
#JWT refresh expiration time interval
#----172800000 (2 days for normal use)
#----120000 (2 minutes for testing)
app.refreshExpirationTime = 120000
#JWT encryption key
app.keyGenAlgorithm = HmacSHA256
#Password encryption rounds
app.encryptionRounds = 12

#---Database related configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/telusko1
spring.datasource.username=postgres
#spring.datasource.password=12345#@
spring.datasource.password=G123k#@.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

